import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { StorageKeys } from "@/lib/localStore";
import { useAppStore } from "@/lib/store";

export type Lang = "en" | "pl" | "no" | "es";

export const STRINGS = {
  en: {
    privateClient:    "PRIVATE CLIENT",
    totalWealth:      "TOTAL WEALTH",
    platinum:         "PLATINUM",
    addFunds:         "+ Add Funds",
    transfer:         "↗ Transfer",
    forecast:         "FORECAST",
    request:          "REQUEST",
    invest:           "INVEST",
    cards:            "CARDS",
    cashFlow:         "CASH FLOW",
    recentOperations: "Recent Operations",
    seeAll:           "See All",
    home:             "HOME",
    visualTheme:      "VISUAL THEME",
    obsidianGold:     "Obsidian Gold",
    arcticPlatinum:   "Arctic Platinum",
    graphiteEmerald:  "Graphite Emerald",
    dark:             "DARK",
    light:            "LIGHT",
    medium:           "MED",
    appPreferences:   "App Preferences",
    personalise:      "Personalise your experience",
    visualExperience: "Visual Experience",
    themeDesc:        "Each palette is crafted around a psychological luxury archetype",
    localisation:     "Localisation",
    language:         "Language",
    primaryCurrency:  "Primary Currency",
    privacyExp:       "Privacy Experience",
    hideBalances:     "Hide Balances",
    hideBalancesDesc: "Blur amounts in public",
    appLock:          "App Lock",
    appLockDesc:      "Require auth on resume",
    edit:             "Edit",
    active:           "ACTIVE",
    sovereignDark:    "SOVEREIGN DARK",
    pristineLight:    "PRISTINE LIGHT",
    forestPower:      "FOREST POWER",
    powerPrestige:    "Power · Prestige · Depth",
    clarityTrust:     "Clarity · Trust · Precision",
    growthMastery:    "Growth · Mastery · Nature",
    obsidianDesc:     "Forged in midnight. Sealed in gold. The palette of authority — timeless like a vault, warm like a flame.",
    platinumDesc:     "The luminance of crystalline wealth. Light as the horizon at dawn — pure, transparent, and uncompromising.",
    emeraldDesc:      "Ancient authority of rare earth. Emerald reserves run deep — where nature and capital converge, wealth compounds.",
    themeUpdated:     "Theme Updated",
    themeActive:      "is now active.",
    languageSet:      "Language Updated",
    send:                  "SEND",
    messages:              "CHAT",
    currencies:            "CURRENCIES",
    manageCurrencies:      "MANAGE CURRENCIES",
    addCurrency:           "Add Currency",
    primaryBadge:          "PRIMARY",
    setPrimary:            "Set primary",
    removeCurrency:        "Remove",
    selectCurrency:        "SELECT CURRENCY",
    exchange:              "EXCHANGE",
    currencyExchange:      "CURRENCY EXCHANGE",
    amount:                "Amount...",
    convert:               "CONVERT",
    received:              "Received",
    errorPrefix:           "Error: ",
    yourCards:             "YOUR CARDS",
    activeCards:           "active",
    noCards:               "NONE",
    activeStatus:          "ACTIVE",
    topupLoginAgain:       "Please log in again.",
    topupEnterValidAmount: "Enter a valid amount.",
    topupStripeError:      "Stripe server error.",
    topupVerifying:        "Verifying payment...",
    topupPleaseWait:       "Please wait a moment.",
    topupPaymentConfirmed: "Payment confirmed!",
    topupAddedToWallet:    "Added to your {cur} wallet.",
    topupBalancePending:   "Your balance will update automatically after Stripe confirms the payment (a few seconds).",
    topupBackToWallet:     "Back to wallet",
    topupPaymentCanceled:  "Payment canceled",
    topupNothingCharged:   "Nothing was charged to your card.",
    topupTryAgain:         "Try again",
    topupBackToHome:       "Back to home",
    topupTitle:            "Add Funds",
    topupSelectCurrency:   "SELECT CURRENCY",
    topupEnterAmountLabel: "ENTER AMOUNT",
    topupYoullAdd:         "YOU'LL ADD",
    topupRedirecting:      "Redirecting...",
    topupAddViaCard:       "Add via card",
    topupStripeNote:       "Balance updates automatically after Stripe confirms your payment.",
    unknownError:          "An unknown error occurred.",
    agreements:            "CONTRACTS",
    agreeTitle:            "Contracts",
    agreeNewBtn:           "+ New Contract",
    agreeTabActive:        "Active",
    agreeTabConfirm:       "To Confirm",
    agreeTabDone:          "Completed",
    agreeTabDispute:       "Disputes",
    agreeEmpty:            "No contracts yet",
    agreeEmptyDesc:        "Create a service agreement with another user.",
    agreeOpenBtn:          "Open",
    agreeStatusPending:    "Awaiting acceptance",
    agreeStatusAccepted:   "Accepted",
    agreeStatusFunded:     "Funds held",
    agreeStatusInProgress: "In progress",
    agreeStatusSubmitted:  "Awaiting confirmation",
    agreeStatusCompleted:  "Confirmed",
    agreeStatusReleased:   "Settled",
    agreeStatusDisputed:   "Dispute",
    agreeStatusCancelled:  "Cancelled",
    agreeNewTitle:         "New Contract",
    agreeFieldTitle:       "Title",
    agreeFieldDesc:        "Description",
    agreeFieldWorker:      "Service provider",
    agreeFieldCategory:    "Category",
    agreeFieldAmount:      "Amount",
    agreeFieldCurrency:    "Currency",
    agreeFieldDeadline:    "Deadline",
    agreeFieldTerms:       "Completion conditions",
    agreeFieldProof:       "Required proof",
    agreeProofPhoto:       "Photo proof",
    agreeProofNote:        "Written note",
    agreeSendBtn:          "Send for acceptance",
    agreeFundNote:         "Funds will be held in your sandbox wallet and released only after you confirm completion.",
    agreeDisputeNote:      "In case of a dispute, contact support.",
    agreeBtnAccept:        "Accept contract",
    agreeBtnSubmit:        "Mark as done",
    agreeBtnFund:          "Hold funds",
    agreeBtnConfirm:       "Confirm completion",
    agreeBtnDispute:       "Report a problem",
    agreeBtnCancel:        "Cancel",
    agreeChatPlaceholder:  "Message about the contract…",
    agreeSendMsg:          "Send",
    agreeEvents:           "History",
    agreeEvtCreated:       "Agreement created",
    agreeEvtAccepted:      "Agreement accepted",
    agreeEvtFunded:        "Funds held in escrow",
    agreeEvtSubmitted:     "Work submitted",
    agreeEvtProofImage:    "Proof image attached",
    agreeEvtCompleted:     "Completion confirmed",
    agreeEvtReleased:      "Funds released to worker",
    agreeEvtDisputed:      "Dispute raised",
    agreeEvtCancelled:     "Agreement cancelled",
    agreeDisputePlaceholder: "Describe the issue…",
    agreeSubmitPlaceholder:  "Describe what you did…",
    agreePlaceholderTitle:   "e.g. Dog walking, Monday morning",
    agreePlaceholderDesc:    "Detailed description of the service…",
    agreePlaceholderWorker:  "Search by name, email or handle…",
    agreePlaceholderTerms:   "What constitutes successful completion…",
    agreeNoFunds:          "Insufficient balance",
    agreeErrNotFound:      "Agreement not found",
    agreeErrNoAccess:      "No access",
    agreeErrFailedAccept:  "Failed to accept",
    agreeErrFailedSubmit:  "Failed to submit",
    agreeErrFailedFund:    "Failed to hold funds",
    agreeErrFailedConfirm: "Failed to confirm",
    agreeErrFailedDispute: "Failed to open dispute",
    agreeErrImageSize:     "Image must be under 25 MB",
    agreeErrFailedPropose: "Failed to send change proposal",
    agreeErrFailedApply:          "Failed to accept change",
    agreeErrFailedReject:         "Failed to reject change",
    agreeErrFundsAlreadyReleased: "Funds have already been released",
    agreeErrSelfContract:         "Creator and worker cannot be the same person",
    agreeErrNotLoggedIn:          "Not logged in",
    agreeErrSaveFailed:           "Error saving agreement",
    agreeContractChat:     "Contract chat",
    agreeFrom:             "Creator",
    agreeTo:               "Worker",
    agreeDeadline:         "Deadline",
    agreeAmount:           "Amount",
    agreeCategory:         "Category",
    agreeCatDog:           "Dog walking",
    agreeCatTransport:     "Transport",
    agreeCatRepair:        "Repair / handyman",
    agreeCatCleaning:      "Cleaning",
    agreeCatShopping:      "Shopping",
    agreeCatOther:         "Other",
    agreeOpenContract:     "Open contract",
    agreeNewContract:      "New contract",
    agreeInChatBtn:        "Contract",
    agreeTmplSection:       "Choose a template",
    agreeTmplDog:           "Dog walking",
    agreeTmplCleaning:      "Cleaning",
    agreeTmplTransport:     "Transport",
    agreeTmplMoving:        "Moving help",
    agreeTmplRepair:        "Repair",
    agreeTmplShopping:      "Shopping",
    agreeTmplCare:          "Caregiving",
    agreeTmplLoan:          "Item loan",
    agreeTmplOther:         "Other",
    agreeTmplDogTerms:      "The worker will walk the dog for at least 30 minutes. Proof: a short note or photo after the walk.",
    agreeTmplCleaningTerms: "The worker will clean the specified rooms as agreed. Proof: photo after cleaning or written note.",
    agreeTmplTransportTerms:"The worker will pick up and deliver the specified person/items on time, per the agreed route.",
    agreeTmplMovingTerms:   "The worker will help with packing and transporting items. Creator confirms after completion.",
    agreeTmplRepairTerms:   "The worker will repair the specified item. Proof: photo after repair or demonstration it works.",
    agreeTmplShoppingTerms: "The worker will purchase the specified items and deliver them. Proof: receipt or photo of goods.",
    agreeTmplCareTerms:     "The worker will provide care for the agreed time. Proof: written note about the session.",
    agreeTmplLoanTerms:     "The item is loaned for the period specified in this agreement and returned in undamaged condition.",
    agreeTmplOtherTerms:    "The worker will perform the service per individual arrangements. Proof as required by the creator.",
    agreeAiHelperBtn:       "Help write terms",
    agreeDepositToggle:     "Add deposit / security",
    agreeDepositAmount:     "Deposit amount",
    agreeDepositCurrency:   "Deposit currency",
    agreeDepositReturnRule: "Return condition",
    agreeDepositPlaceholder:"e.g. Deposit returned when item is returned undamaged.",
    agreeCompletionCriteria:            "What counts as completion",
    agreeCompletionCriteriaPlaceholder: "Describe exactly what will constitute successful completion…",
    agreeSecuritySection:               "Security guidelines",
    agreeSecurityText:                  "Be precise about what constitutes completion. Funds are released only after you confirm. Keep all arrangements in the app.",
    agreeSelfError:                     "You cannot create a contract with yourself",
    agreeWarnHighAmount:                "High amount detected. Verify the other party or start with a smaller amount.",
    agreeWarnNoPhoto:                   "Without a photo it's harder to prove completion. Consider requiring photo proof.",
    agreeWorkerNoHistory:               "This person has no history yet. Consider starting with a smaller amount.",
    agreeAcceptanceSection:             "Acceptance status",
    agreeCreatorAcceptedLabel:          "Creator: accepted",
    agreeWorkerAcceptedLabel:           "Worker: accepted",
    agreeCreatorPendingLabel:           "Creator: pending",
    agreeWorkerPendingLabel:            "Worker: pending",
    agreeBtnWorkerAccept:               "I accept the contract terms",
    agreeFundAvailable:                 "Available",
    agreeFundShortfall:                 "Shortfall",
    agreeFundHoldNote2:                 "Funds will be held — worker receives them only after your confirmation",
    agreeSubmitConfirmCheck:            "I confirm I completed the task per the agreement conditions",
    agreeSubmitPhotoRequired:           "Photo is required as proof of completion",
    agreeProofCardTitle:                "Completion proof",
    agreeProofCardNote:                 "Worker's note",
    agreeProofCardPhoto:                "Photo",
    agreeProofCardDate:                 "Submitted",
    agreeDisputeReason:                 "Reason",
    agreeDisputeReason1:                "Service not performed",
    agreeDisputeReason2:                "Partially completed",
    agreeDisputeReason3:                "Proof is unclear",
    agreeDisputeReason4:                "Deadline mismatch",
    agreeDisputeReason5:                "Amount mismatch",
    agreeDisputeReason6:                "Other reason",
    agreeTimelineTitle:                 "Agreement progress",
    agreeTimelineStep1:                 "Created",
    agreeTimelineStep2:                 "Accepted",
    agreeTimelineStep3:                 "Funds held",
    agreeTimelineStep4:                 "Work submitted",
    agreeTimelineStep5:                 "Confirmation",
    agreeTimelineStep6:                 "Funds released",
    agreeChatSecurityNote:              "Keep all communication in the app for your protection",
    agreeChangeBtn:                     "Propose a change",
    agreeChangeTitle:                   "Propose contract change",
    agreeChangeNewDeadline:             "New deadline (optional)",
    agreeChangeNewAmount:               "New amount (optional)",
    agreeChangeAmountLocked:            "Amount cannot be changed while funds are held",
    agreeChangeNewTerms:                "New terms (optional)",
    agreeChangeNote:                    "Note for the other party",
    agreeChangeSend:                    "Send proposal",
    agreeChangePending:                 "Pending response",
    agreeChangeAccept:                  "Accept change",
    agreeChangeReject:                  "Reject",
    agreeChangeAccepted:                "Change accepted",
    agreeChangeRejected:                "Change rejected",
    agreeEvtChangeProposed:             "Change proposed",
    agreeEvtChangeAccepted:             "Change accepted",
    agreeEvtChangeRejected:             "Change rejected",
    agreeEvtWorkerAccepted:             "Worker accepted terms",
    agreeSelectPlaceholder:             "— select —",
    agreePhotoSelected:                 "Photo selected ✓",
    agreeRateBtn:                       "Rate this collaboration",
    ratingModalTitle:                   "Rate the collaboration",
    ratingModalStars:                   "Your rating",
    ratingModalComment:                 "Leave a comment (optional)",
    ratingModalOnTime:                  "Was it done on time?",
    ratingModalRecommend:               "Would you recommend this person?",
    ratingModalSubmit:                  "Submit rating",
    ratingModalSkip:                    "Skip for now",
    ratingModalThanks:                  "Thank you for your rating!",
    ratingNoRatings:                    "No ratings yet",
    ratingAvg:                          "Average rating",
    ratingCount:                        "Ratings",
    ratingRecommended:                  "Recommended",
    ratingCompleted:                    "Completed",
    levelNew:                           "New",
    levelVerified:                      "Verified",
    levelTrusted:                       "Trusted",
    levelTop:                           "Top Worker",
    levelSuper:                         "Super Helper",
    reputationSection:                  "Reputation",
    agreeWorkerReputation:              "Worker reputation",
    ratingYes:                          "Yes",
    ratingNo:                           "No",
    ratingCompletedAgreements:          "Completed",
    ratingBuildReputation:              "Complete agreements to build your reputation.",
    agreeStepper1:        "1. Task",
    agreeStepper2:        "2. Pricing",
    agreeStepper3:        "3. Confirm",
    agreeSecurePayTitle:  "Secure payment",
    agreeSecurePayDesc:   "Funds are blocked and released only after completion is confirmed.",
    agreeNewCategories:   "Choose category",
    agreeCatRenovation:   "Renovation",
    agreeCatCarpenter:    "Carpenter",
    agreeCatJoiner:       "Joiner",
    agreePricingType:     "Pricing method",
    agreePricingFixed:    "Fixed price",
    agreePricingM2:       "Price per m\u00B2",
    agreePricingHourly:   "Hourly",
    agreePricingPiece:    "Per piece",
    agreePricingMixed:    "Mixed",
    agreePricingDetails:  "Pricing details",
    agreePricingSummary:  "Cost summary",
    agreePricingArea:     "Area (m\u00B2)",
    agreePricingPriceM2:  "Price per 1 m\u00B2",
    agreePricingMaterials:"Materials",
    agreePricingExtra:    "Extra costs",
    agreePricingLabor:    "Labor",
    agreePricingTotal:    "Total",
    agreeFixedFinalPrice: "Fixed final price",
    agreeHourlyRate:      "Hourly rate",
    agreeHoursCount:      "Number of hours",
    agreeHoursMax:        "Max hours limit",
    agreePieceCount:      "Piece count",
    agreePiecePrice:      "Price per piece",
    agreePieceDesc:       "Item description",
    agreeMixedTitle:      "Mixed pricing",
    agreeWorkScopeTitle:  "Work scope",
    agreeWorkScopeWhat:   "What exactly needs to be done",
    agreeWorkScopeExcluded:"What is NOT included",
    agreeMaterialsBy:     "Who provides materials",
    agreeMaterialsClient: "Client",
    agreeMaterialsWorker: "Worker",
    agreeMaterialsSeparate:"Separate billing",
    agreeMaterialsIncluded:"Included in price",
    agreeConditionsTitle: "Acceptance conditions",
    agreeAiHelperBtnShort:"AI: Help write",
    agreeStagesTitle:     "Work stages",
    agreeAddStage:        "Add stage",
    agreeProofsTitle:     "Required proofs",
    agreeProofAfter:      "Photo of completed work",
    agreeProofBefore:     "Photo before start",
    agreeProofMessage:    "Completion message",
    agreeProofBothSides:  "Both parties confirm",
    agreeProofLocation:   "Location / timestamp",
    agreeDeadlineTitle:   "Deadline",
    agreeDeadlineToday:   "Today",
    agreeDeadlineTomorrow:"Tomorrow",
    agreeDeadline7d:      "7 days",
    agreeDeadline14d:     "14 days",
    agreeDeadlineCustom:  "Pick date",
    agreeSummaryTitle:    "Agreement summary",
    agreeCreateBtn:       "Create ideal contract",
    notifAll:             "All",
    notifMessages:        "Messages",
    notifPayments:        "Payments",
    notifContracts:       "Contracts",
    notifSystem:          "System",
    notifSecurity:        "Security",
    notifEmpty:           "No notifications",
    notifEmptyDesc:       "Your inbox is clear. Nothing to see here.",
    notifMarkAllRead:     "Mark all as read",
    notifDelivery:        "Delivery Channels",
    notifPerCategory:     "Notification Types",
    notifInApp:           "In-app",
    notifPushToggle:      "Push",
    notifQuietHours:      "Quiet Hours",
    notifQuietFrom:       "From",
    notifQuietTo:         "To",
    notifPrefsSaved:      "Preferences saved",
    notifTestPanel:       "Test Notifications",
    notifTestSend:        "Send Test",
    notifTestSendPush:    "Also send push",
    notifTestTitle:       "Title",
    notifTestMessage:     "Message",
    notifTestCategory:    "Category",
    notifTestPriority:    "Priority",
    notifTestRoute:       "Route (e.g. /messages)",
    notifTestSent:        "Test notification sent",
    notifTestTargetUser:  "Target user ID",
    notifPriorityLow:     "Low",
    notifPriorityNormal:  "Normal",
    notifPriorityHigh:    "High",
    notifPriorityCritical:"Critical",
    notifFilterAll:       "All",
    notifFilterNew:       "New",
    notifFilterImportant: "Important",
    notifDelete:          "Delete",
    notifQuietModeTitle:  "Quiet Mode",
    notifImportantOnly:   "Important only during quiet hours",
    notifDailySummary:    "Daily summary",
    notifQuietModeDesc:   "Only critical & high-priority alerts will notify you during quiet hours.",
    notifScenarioGroupedMsg: "3 Messages (Grouped)",
    notifClearQuiet:      "Clear",
    notifQuietHoursTitle: "Quiet hours",
  },
  pl: {
    privateClient:    "KLIENT PRYWATNY",
    totalWealth:      "ŁĄCZNY MAJĄTEK",
    platinum:         "PLATYNA",
    addFunds:         "+ Dodaj Środki",
    transfer:         "↗ Przelew",
    forecast:         "PROGNOZA",
    request:          "ŻĄDANIE",
    invest:           "INWESTUJ",
    cards:            "KARTY",
    cashFlow:         "PRZEPŁYWY",
    recentOperations: "Ostatnie Operacje",
    seeAll:           "Pokaż Wszystkie",
    home:             "DOM",
    visualTheme:      "MOTYW WIZUALNY",
    obsidianGold:     "Obsydian Złoto",
    arcticPlatinum:   "Arktyczna Platyna",
    graphiteEmerald:  "Grafit Szmaragd",
    dark:             "CIEMNY",
    light:            "JASNY",
    medium:           "ŚREDNI",
    appPreferences:   "Ustawienia Aplikacji",
    personalise:      "Dostosuj swoje doświadczenie",
    visualExperience: "Doświadczenie Wizualne",
    themeDesc:        "Każda paleta zbudowana wokół psychologicznego archetypu luksusu",
    localisation:     "Lokalizacja",
    language:         "Język",
    primaryCurrency:  "Waluta Podstawowa",
    privacyExp:       "Prywatność",
    hideBalances:     "Ukryj Salda",
    hideBalancesDesc: "Zamazuj kwoty publicznie",
    appLock:          "Blokada Aplikacji",
    appLockDesc:      "Wymagaj autoryzacji po wznowieniu",
    edit:             "Edytuj",
    active:           "AKTYWNY",
    sovereignDark:    "MROCZNA SUWERENNOŚĆ",
    pristineLight:    "NIESKAZITELNE ŚWIATŁO",
    forestPower:      "MOC LASU",
    powerPrestige:    "Władza · Prestiż · Głębia",
    clarityTrust:     "Klarowność · Zaufanie · Precyzja",
    growthMastery:    "Wzrost · Mistrzostwo · Natura",
    obsidianDesc:     "Wykuty o północy. Zapieczętowany złotem. Paleta autorytetu — ponadczasowy jak skarbiec, ciepły jak płomień.",
    platinumDesc:     "Blask krystalicznego bogactwa. Lekki jak horyzont o świcie — czysty, przejrzysty i bezkompromisowy.",
    emeraldDesc:      "Starożytny autorytet rzadkiej ziemi. Szmaragdowe rezerwy sięgają głęboko — tam gdzie natura i kapitał się spotykają, bogactwo narasta.",
    themeUpdated:     "Motyw Zaktualizowany",
    themeActive:      "jest teraz aktywny.",
    languageSet:      "Język Zaktualizowany",
    send:                  "WYŚLIJ",
    messages:              "CZAT",
    currencies:            "WALUTY",
    manageCurrencies:      "ZARZĄDZAJ WALUTAMI",
    addCurrency:           "Dodaj walutę",
    primaryBadge:          "GŁÓWNA",
    setPrimary:            "Ustaw główną",
    removeCurrency:        "Usuń",
    selectCurrency:        "WYBIERZ WALUTĘ",
    exchange:              "WYMIEŃ",
    currencyExchange:      "WYMIANA WALUT",
    amount:                "Kwota...",
    convert:               "WYMIEŃ",
    received:              "Otrzymano",
    errorPrefix:           "Błąd: ",
    yourCards:             "TWOJE KARTY",
    activeCards:           "aktywne",
    noCards:               "BRAK",
    activeStatus:          "AKTYWNE",
    topupLoginAgain:       "Zaloguj się ponownie.",
    topupEnterValidAmount: "Podaj prawidłową kwotę.",
    topupStripeError:      "Błąd serwera Stripe.",
    topupVerifying:        "Weryfikacja płatności...",
    topupPleaseWait:       "Proszę czekać (kilka sekund).",
    topupPaymentConfirmed: "Płatność potwierdzona!",
    topupAddedToWallet:    "Dodano do Twojego portfela {cur}.",
    topupBalancePending:   "Twoje saldo zostanie zaktualizowane automatycznie po potwierdzeniu płatności przez Stripe (kilka sekund).",
    topupBackToWallet:     "Wróć do portfela",
    topupPaymentCanceled:  "Płatność anulowana",
    topupNothingCharged:   "Nic nie zostało pobrane z karty.",
    topupTryAgain:         "Spróbuj ponownie",
    topupBackToHome:       "Wróć do głównej",
    topupTitle:            "Dodaj środki",
    topupSelectCurrency:   "WYBIERZ WALUTĘ",
    topupEnterAmountLabel: "WPISZ KWOTĘ",
    topupYoullAdd:         "ZASILEISZ KONTO O",
    topupRedirecting:      "Przekierowanie...",
    topupAddViaCard:       "Dodaj przez kartę",
    topupStripeNote:       "Saldo zostanie zaktualizowane automatycznie po potwierdzeniu płatności przez Stripe.",
    unknownError:          "Wystąpił nieznany błąd.",
    agreements:            "UMOWA",
    agreeTitle:            "Umowy",
    agreeNewBtn:           "+ Nowa umowa",
    agreeTabActive:        "Aktywne",
    agreeTabConfirm:       "Do potwierdzenia",
    agreeTabDone:          "Zakończone",
    agreeTabDispute:       "Sporne",
    agreeEmpty:            "Nie masz jeszcze umów",
    agreeEmptyDesc:        "Utwórz zlecenie z innym użytkownikiem.",
    agreeOpenBtn:          "Otwórz",
    agreeStatusPending:    "Czeka na przyjęcie",
    agreeStatusAccepted:   "Przyjęta",
    agreeStatusFunded:     "Środki zablokowane",
    agreeStatusInProgress: "W trakcie",
    agreeStatusSubmitted:  "Wykonanie zgłoszone",
    agreeStatusCompleted:  "Potwierdzona",
    agreeStatusReleased:   "Rozliczona",
    agreeStatusDisputed:   "Problem",
    agreeStatusCancelled:  "Anulowana",
    agreeNewTitle:         "Nowa umowa",
    agreeFieldTitle:       "Tytuł",
    agreeFieldDesc:        "Opis",
    agreeFieldWorker:      "Wykonawca",
    agreeFieldCategory:    "Kategoria",
    agreeFieldAmount:      "Kwota",
    agreeFieldCurrency:    "Waluta",
    agreeFieldDeadline:    "Termin wykonania",
    agreeFieldTerms:       "Warunki wykonania",
    agreeFieldProof:       "Wymagane dowody",
    agreeProofPhoto:       "Zdjęcie wykonanej pracy",
    agreeProofNote:        "Notatka pisemna",
    agreeSendBtn:          "Wyślij do akceptacji",
    agreeFundNote:         "Środki zostaną zablokowane w Twoim portfelu sandbox i wypłacone dopiero po potwierdzeniu wykonania.",
    agreeDisputeNote:      "W przypadku sporu skontaktuj się z supportem.",
    agreeBtnAccept:        "Przyjmij umowę",
    agreeBtnSubmit:        "Zgłoś wykonanie",
    agreeBtnFund:          "Zablokuj środki",
    agreeBtnConfirm:       "Potwierdzam wykonanie",
    agreeBtnDispute:       "Zgłoś problem",
    agreeBtnCancel:        "Anuluj",
    agreeChatPlaceholder:  "Wiadomość dot. umowy…",
    agreeSendMsg:          "Wyślij",
    agreeEvents:           "Historia",
    agreeEvtCreated:       "Umowa utworzona",
    agreeEvtAccepted:      "Umowa zaakceptowana",
    agreeEvtFunded:        "Środki zablokowane w escrow",
    agreeEvtSubmitted:     "Praca zgłoszona",
    agreeEvtProofImage:    "Załączono zdjęcie dowodu",
    agreeEvtCompleted:     "Wykonanie potwierdzone",
    agreeEvtReleased:      "Środki przekazane wykonawcy",
    agreeEvtDisputed:      "Zgłoszono spór",
    agreeEvtCancelled:     "Umowa anulowana",
    agreeDisputePlaceholder: "Opisz problem…",
    agreeSubmitPlaceholder:  "Opisz co zostało zrobione…",
    agreePlaceholderTitle:   "Np. Wyprowadzenie psa w poniedziałek rano",
    agreePlaceholderDesc:    "Opisz krótko, co ma zostać wykonane",
    agreePlaceholderWorker:  "Szukaj po imieniu, e-mailu lub nazwie użytkownika",
    agreePlaceholderTerms:   "Co będzie dowodem ukończenia zlecenia…",
    agreeNoFunds:          "Niewystarczające saldo",
    agreeErrNotFound:      "Umowa nie istnieje",
    agreeErrNoAccess:      "Brak dostępu",
    agreeErrFailedAccept:  "Nie udało się zaakceptować",
    agreeErrFailedSubmit:  "Nie udało się przesłać",
    agreeErrFailedFund:    "Nie udało się zablokować środków",
    agreeErrFailedConfirm: "Nie udało się potwierdzić",
    agreeErrFailedDispute: "Nie udało się zgłosić sporu",
    agreeErrImageSize:     "Zdjęcie musi być mniejsze niż 25 MB",
    agreeErrFailedPropose: "Nie udało się wysłać propozycji zmiany",
    agreeErrFailedApply:          "Nie udało się zaakceptować zmiany",
    agreeErrFailedReject:         "Nie udało się odrzucić zmiany",
    agreeErrFundsAlreadyReleased: "Środki zostały już wypłacone",
    agreeErrSelfContract:         "Zleceniodawca i wykonawca nie mogą być tą samą osobą",
    agreeErrNotLoggedIn:          "Nie jesteś zalogowany",
    agreeErrSaveFailed:           "Błąd zapisu umowy",
    agreeContractChat:     "Czat umowy",
    agreeFrom:             "Zleceniodawca",
    agreeTo:               "Wykonawca",
    agreeDeadline:         "Termin",
    agreeAmount:           "Kwota",
    agreeCategory:         "Kategoria",
    agreeCatDog:           "Wyprowadzanie psa",
    agreeCatTransport:     "Transport",
    agreeCatRepair:        "Naprawa / usługa",
    agreeCatCleaning:      "Sprzątanie",
    agreeCatShopping:      "Zakupy",
    agreeCatOther:         "Inne",
    agreeOpenContract:     "Otwórz umowę",
    agreeNewContract:      "Nowa umowa",
    agreeInChatBtn:        "Umowa",
    agreeTmplSection:       "Wybierz szablon",
    agreeTmplDog:           "Wyprowadzenie psa",
    agreeTmplCleaning:      "Sprzątanie",
    agreeTmplTransport:     "Transport",
    agreeTmplMoving:        "Przeprowadzka",
    agreeTmplRepair:        "Naprawa",
    agreeTmplShopping:      "Zakupy",
    agreeTmplCare:          "Opieka",
    agreeTmplLoan:          "Pożyczka rzeczy",
    agreeTmplOther:         "Inne",
    agreeTmplDogTerms:      "Wykonawca zobowiązuje się wyprowadzić psa na spacer minimum 30 minut. Dowód: krótka notatka lub zdjęcie po spacerze.",
    agreeTmplCleaningTerms: "Wykonawca posprząta wskazane pomieszczenia zgodnie z ustaleniami. Dowód: zdjęcie po sprzątaniu lub pisemna notatka.",
    agreeTmplTransportTerms:"Wykonawca odbierze i dostarczy wskazane osoby/rzeczy na czas, zgodnie z ustalonym terminem i trasą.",
    agreeTmplMovingTerms:   "Wykonawca pomoże przy pakowaniu i transporcie rzeczy. Po zakończeniu zleceniodawca potwierdza wykonanie.",
    agreeTmplRepairTerms:   "Wykonawca dokona naprawy wskazanego sprzętu. Dowód: zdjęcie po naprawie lub demonstracja działania.",
    agreeTmplShoppingTerms: "Wykonawca nabędzie wskazane produkty i dostarczy je do zleceniodawcy. Dowód: paragon lub zdjęcie zakupów.",
    agreeTmplCareTerms:     "Wykonawca sprawuje opiekę przez uzgodniony czas. Po zakończeniu pisemna notatka o przebiegu.",
    agreeTmplLoanTerms:     "Przedmiot zostaje wypożyczony na czas określony w umowie i zwrócony w stanie nienaruszonym.",
    agreeTmplOtherTerms:    "Wykonawca wykona usługę zgodnie z indywidualnymi ustaleniami. Dowód wg wymagań zleceniodawcy.",
    agreeAiHelperBtn:       "Pomóż napisać warunki",
    agreeDepositToggle:     "Dodaj depozyt / kaucję",
    agreeDepositAmount:     "Kwota depozytu",
    agreeDepositCurrency:   "Waluta depozytu",
    agreeDepositReturnRule: "Zasada zwrotu",
    agreeDepositPlaceholder:"Np. Depozyt wraca po oddaniu rzeczy bez uszkodzeń.",
    agreeCompletionCriteria:            "Co oznacza wykonanie",
    agreeCompletionCriteriaPlaceholder: "Opisz dokładnie, co uzna się za ukończenie zadania…",
    agreeSecuritySection:               "Zasady bezpieczeństwa",
    agreeSecurityText:                  "Określ precyzyjnie warunki ukończenia. Środki są wypłacane dopiero po Twojej akceptacji. Wszystkie ustalenia prowadź w aplikacji.",
    agreeSelfError:                     "Nie możesz stworzyć umowy z samym sobą",
    agreeWarnHighAmount:                "Wysoka kwota. Zweryfikuj tę osobę lub zacznij od mniejszej kwoty.",
    agreeWarnNoPhoto:                   "Bez zdjęcia jako dowodu trudniej udowodnić wykonanie. Rozważ wymaganie zdjęcia.",
    agreeWorkerNoHistory:               "Ta osoba nie ma jeszcze historii. Zacznij od mniejszej kwoty.",
    agreeAcceptanceSection:             "Status akceptacji",
    agreeCreatorAcceptedLabel:          "Zleceniodawca: zaakceptowano",
    agreeWorkerAcceptedLabel:           "Wykonawca: zaakceptowano",
    agreeCreatorPendingLabel:           "Zleceniodawca: oczekuje",
    agreeWorkerPendingLabel:            "Wykonawca: oczekuje",
    agreeBtnWorkerAccept:               "Akceptuję warunki umowy",
    agreeFundAvailable:                 "Dostępne",
    agreeFundShortfall:                 "Brakuje",
    agreeFundHoldNote2:                 "Środki zablokowane — wykonawca otrzyma je dopiero po Twoim potwierdzeniu",
    agreeSubmitConfirmCheck:            "Potwierdzam, że wykonałem zadanie zgodnie z warunkami umowy",
    agreeSubmitPhotoRequired:           "Zdjęcie jest wymagane jako dowód wykonania",
    agreeProofCardTitle:                "Dowód wykonania",
    agreeProofCardNote:                 "Notatka wykonawcy",
    agreeProofCardPhoto:                "Zdjęcie",
    agreeProofCardDate:                 "Zgłoszono",
    agreeDisputeReason:                 "Powód sporu",
    agreeDisputeReason1:                "Nie wykonano usługi",
    agreeDisputeReason2:                "Wykonano częściowo",
    agreeDisputeReason3:                "Dowód jest niejasny",
    agreeDisputeReason4:                "Nie zgadza się termin",
    agreeDisputeReason5:                "Nie zgadza się kwota",
    agreeDisputeReason6:                "Inny powód",
    agreeTimelineTitle:                 "Postęp umowy",
    agreeTimelineStep1:                 "Umowa utworzona",
    agreeTimelineStep2:                 "Warunki zaakceptowane",
    agreeTimelineStep3:                 "Środki zablokowane",
    agreeTimelineStep4:                 "Wykonanie zgłoszone",
    agreeTimelineStep5:                 "Potwierdzenie",
    agreeTimelineStep6:                 "Środki przekazane",
    agreeChatSecurityNote:              "Dla bezpieczeństwa trzymaj ustalenia w aplikacji",
    agreeChangeBtn:                     "Zaproponuj zmianę",
    agreeChangeTitle:                   "Propozycja zmiany warunków",
    agreeChangeNewDeadline:             "Nowy termin (opcjonalnie)",
    agreeChangeNewAmount:               "Nowa kwota (opcjonalnie)",
    agreeChangeAmountLocked:            "Kwota nie może być zmieniana, gdy środki są zablokowane",
    agreeChangeNewTerms:                "Nowe warunki (opcjonalnie)",
    agreeChangeNote:                    "Uwaga dla drugiej strony",
    agreeChangeSend:                    "Wyślij propozycję",
    agreeChangePending:                 "Oczekuje na odpowiedź",
    agreeChangeAccept:                  "Akceptuję zmianę",
    agreeChangeReject:                  "Odrzuć",
    agreeChangeAccepted:                "Zmiana zaakceptowana",
    agreeChangeRejected:                "Zmiana odrzucona",
    agreeEvtChangeProposed:             "Zaproponowano zmianę warunków",
    agreeEvtChangeAccepted:             "Zmiana warunków zaakceptowana",
    agreeEvtChangeRejected:             "Zmiana warunków odrzucona",
    agreeEvtWorkerAccepted:             "Wykonawca zaakceptował warunki",
    agreeSelectPlaceholder:             "— wybierz —",
    agreePhotoSelected:                 "Zdjęcie wybrane ✓",
    agreeRateBtn:                       "Oceń współpracę",
    ratingModalTitle:                   "Oceń współpracę",
    ratingModalStars:                   "Twoja ocena",
    ratingModalComment:                 "Komentarz (opcjonalnie)",
    ratingModalOnTime:                  "Czy wykonano na czas?",
    ratingModalRecommend:               "Czy polecasz tę osobę?",
    ratingModalSubmit:                  "Wyślij ocenę",
    ratingModalSkip:                    "Pomiń na razie",
    ratingModalThanks:                  "Dziękujemy za ocenę!",
    ratingNoRatings:                    "Brak ocen",
    ratingAvg:                          "Średnia ocena",
    ratingCount:                        "Oceny",
    ratingRecommended:                  "Polecanych",
    ratingCompleted:                    "Ukończonych",
    levelNew:                           "Nowy",
    levelVerified:                      "Zweryfikowany",
    levelTrusted:                       "Zaufany",
    levelTop:                           "Top wykonawca",
    levelSuper:                         "Super helper",
    reputationSection:                  "Reputacja",
    agreeWorkerReputation:              "Reputacja wykonawcy",
    ratingYes:                          "Tak",
    ratingNo:                           "Nie",
    ratingCompletedAgreements:          "Ukończone",
    ratingBuildReputation:              "Ukończ zlecenia, aby budować swoją reputację.",
    agreeStepper1:        "1. Zadanie",
    agreeStepper2:        "2. Wycena",
    agreeStepper3:        "3. Potwierdzenie",
    agreeSecurePayTitle:  "Bezpieczna płatność",
    agreeSecurePayDesc:   "Środki są blokowane i wypłacane dopiero po potwierdzeniu wykonania.",
    agreeNewCategories:   "Wybierz kategorię",
    agreeCatRenovation:   "Remont",
    agreeCatCarpenter:    "Cieśla",
    agreeCatJoiner:       "Stolarz",
    agreePricingType:     "Sposób wyceny",
    agreePricingFixed:    "Cena stała",
    agreePricingM2:       "Cena za m\u00B2",
    agreePricingHourly:   "Godzinowo",
    agreePricingPiece:    "Za sztukę",
    agreePricingMixed:    "Cena mieszana",
    agreePricingDetails:  "Szczegóły wyceny",
    agreePricingSummary:  "Podsumowanie kosztów",
    agreePricingArea:     "Powierzchnia",
    agreePricingPriceM2:  "Cena za 1 m\u00B2",
    agreePricingMaterials:"Materiały",
    agreePricingExtra:    "Dodatkowe koszty",
    agreePricingLabor:    "Robocizna",
    agreePricingTotal:    "Razem",
    agreeFixedFinalPrice: "Ustalona cena końcowa",
    agreeHourlyRate:      "Stawka za godzinę",
    agreeHoursCount:      "Liczba godzin",
    agreeHoursMax:        "Maksymalny limit godzin",
    agreePieceCount:      "Liczba sztuk",
    agreePiecePrice:      "Cena za sztukę",
    agreePieceDesc:       "Opis elementów",
    agreeMixedTitle:      "Cena mieszana",
    agreeWorkScopeTitle:  "Zakres prac",
    agreeWorkScopeWhat:   "Co dokładnie ma zostać wykonane",
    agreeWorkScopeExcluded:"Czego umowa nie obejmuje",
    agreeMaterialsBy:     "Kto zapewnia materiały",
    agreeMaterialsClient: "Zleceniodawca",
    agreeMaterialsWorker: "Wykonawca",
    agreeMaterialsSeparate:"Osobne rozliczenie",
    agreeMaterialsIncluded:"Wliczone w cenę",
    agreeConditionsTitle: "Warunki wykonania",
    agreeAiHelperBtnShort:"AI: Pomóż napisać",
    agreeStagesTitle:     "Etapy pracy",
    agreeAddStage:        "Dodaj etap",
    agreeProofsTitle:     "Wymagane dowody",
    agreeProofAfter:      "Zdjęcie wykonanej pracy",
    agreeProofBefore:     "Zdjęcie przed rozpoczęciem",
    agreeProofMessage:    "Wiadomość z opisem wykonania",
    agreeProofBothSides:  "Potwierdzenie obu stron",
    agreeProofLocation:   "Lokalizacja / czas wykonania",
    agreeDeadlineTitle:   "Termin realizacji",
    agreeDeadlineToday:   "Dzisiaj",
    agreeDeadlineTomorrow:"Jutro",
    agreeDeadline7d:      "7 dni",
    agreeDeadline14d:     "14 dni",
    agreeDeadlineCustom:  "Wybierz datę",
    agreeSummaryTitle:    "Podsumowanie umowy",
    agreeCreateBtn:       "Utwórz idealną umowę",
    notifAll:             "Wszystkie",
    notifMessages:        "Wiadomości",
    notifPayments:        "Płatności",
    notifContracts:       "Umowy",
    notifSystem:          "System",
    notifSecurity:        "Bezpieczeństwo",
    notifEmpty:           "Brak powiadomień",
    notifEmptyDesc:       "Skrzynka jest pusta. Nic do przeczytania.",
    notifMarkAllRead:     "Oznacz wszystkie jako przeczytane",
    notifDelivery:        "Kanały dostarczania",
    notifPerCategory:     "Rodzaje powiadomień",
    notifInApp:           "W aplikacji",
    notifPushToggle:      "Push",
    notifQuietHours:      "Ciche godziny",
    notifQuietFrom:       "Od",
    notifQuietTo:         "Do",
    notifPrefsSaved:      "Preferencje zapisane",
    notifTestPanel:       "Test powiadomień",
    notifTestSend:        "Wyślij test",
    notifTestSendPush:    "Wyślij też push",
    notifTestTitle:       "Tytuł",
    notifTestMessage:     "Wiadomość",
    notifTestCategory:    "Kategoria",
    notifTestPriority:    "Priorytet",
    notifTestRoute:       "Ścieżka (np. /messages)",
    notifTestSent:        "Testowe powiadomienie wysłane",
    notifTestTargetUser:  "ID użytkownika docelowego",
    notifPriorityLow:     "Niski",
    notifPriorityNormal:  "Normalny",
    notifPriorityHigh:    "Wysoki",
    notifPriorityCritical:"Krytyczny",
    notifFilterAll:       "Wszystkie",
    notifFilterNew:       "Nowe",
    notifFilterImportant: "Ważne",
    notifDelete:          "Usuń",
    notifQuietModeTitle:  "Tryb cichy",
    notifImportantOnly:   "Tylko ważne w trybie cichym",
    notifDailySummary:    "Dzienne podsumowanie",
    notifQuietModeDesc:   "Tylko alerty krytyczne i o wysokim priorytecie będą Cię powiadamiać w trybie cichym.",
    notifScenarioGroupedMsg: "3 wiadomości (zgrupowane)",
    notifClearQuiet:      "Wyczyść",
    notifQuietHoursTitle: "Godziny ciszy",
  },
  no: {
    privateClient:    "PRIVAT KLIENT",
    totalWealth:      "TOTAL FORMUE",
    platinum:         "PLATINA",
    addFunds:         "+ Legg til midler",
    transfer:         "↗ Overfør",
    forecast:         "PROGNOSE",
    request:          "FORESPØRSEL",
    invest:           "INVESTER",
    cards:            "KORT",
    cashFlow:         "KONTANTSTRØM",
    recentOperations: "Siste transaksjoner",
    seeAll:           "Se alle",
    home:             "HJEM",
    visualTheme:      "VISUELT TEMA",
    obsidianGold:     "Obsidian Gull",
    arcticPlatinum:   "Arktisk Platina",
    graphiteEmerald:  "Grafitt Smaragd",
    dark:             "MØRK",
    light:            "LYS",
    medium:           "MIDDELS",
    appPreferences:   "App-innstillinger",
    personalise:      "Tilpass din opplevelse",
    visualExperience: "Visuell opplevelse",
    themeDesc:        "Hvert palett er laget rundt en psykologisk luksusarketype",
    localisation:     "Lokalisering",
    language:         "Språk",
    primaryCurrency:  "Primærvaluta",
    privacyExp:       "Personvern",
    hideBalances:     "Skjul saldo",
    hideBalancesDesc: "Uklare beløp offentlig",
    appLock:          "App-lås",
    appLockDesc:      "Krev autentisering ved gjenopptakelse",
    edit:             "Rediger",
    active:           "AKTIV",
    sovereignDark:    "SUVERENT MØRKT",
    pristineLight:    "PRISTINT LYS",
    forestPower:      "SKOGKRAFT",
    powerPrestige:    "Makt · Prestisje · Dybde",
    clarityTrust:     "Klarhet · Tillit · Presisjon",
    growthMastery:    "Vekst · Mestring · Natur",
    obsidianDesc:     "Smidd ved midnatt. Forseglet i gull. Autoritetens palett — tidløs som et hvelv, varm som en flamme.",
    platinumDesc:     "Glansen av krystallsk rikdom. Lett som horisonten ved daggry — ren, gjennomsiktig og kompromissløs.",
    emeraldDesc:      "Gammel autoritet av sjeldne jordarter. Smaragdreserver strekker seg dypt — der natur og kapital konvergerer, vokser rikdommen.",
    themeUpdated:     "Tema oppdatert",
    themeActive:      "er nå aktivt.",
    languageSet:      "Språk oppdatert",
    send:                  "SEND",
    messages:              "CHAT",
    currencies:            "VALUTAER",
    manageCurrencies:      "ADMINISTRER VALUTAER",
    addCurrency:           "Legg til valuta",
    primaryBadge:          "PRIMÆR",
    setPrimary:            "Angi som primær",
    removeCurrency:        "Fjern",
    selectCurrency:        "VELG VALUTA",
    exchange:              "VEKSLE",
    currencyExchange:      "VALUTAVEKSLING",
    amount:                "Beløp...",
    convert:               "KONVERTER",
    received:              "Mottatt",
    errorPrefix:           "Feil: ",
    yourCards:             "DINE KORT",
    activeCards:           "aktive",
    noCards:               "INGEN",
    activeStatus:          "AKTIVE",
    topupLoginAgain:       "Logg inn igjen.",
    topupEnterValidAmount: "Skriv inn et gyldig beløp.",
    topupStripeError:      "Stripe-serverfeil.",
    topupVerifying:        "Verifiserer betaling...",
    topupPleaseWait:       "Vennligst vent (noen sekunder).",
    topupPaymentConfirmed: "Betaling bekreftet!",
    topupAddedToWallet:    "Lagt til i din {cur}-lommebok.",
    topupBalancePending:   "Saldoen din oppdateres automatisk etter at Stripe bekrefter betalingen (noen sekunder).",
    topupBackToWallet:     "Tilbake til lommeboken",
    topupPaymentCanceled:  "Betaling avbrutt",
    topupNothingCharged:   "Ingenting ble belastet kortet ditt.",
    topupTryAgain:         "Prøv igjen",
    topupBackToHome:       "Tilbake til start",
    topupTitle:            "Legg til midler",
    topupSelectCurrency:   "VELG VALUTA",
    topupEnterAmountLabel: "SKRIV INN BELØP",
    topupYoullAdd:         "DU LEGGER TIL",
    topupRedirecting:      "Omdirigerer...",
    topupAddViaCard:       "Legg til via kort",
    topupStripeNote:       "Saldoen oppdateres automatisk etter at Stripe bekrefter betalingen.",
    unknownError:          "En ukjent feil oppstod.",
    agreements:            "AVTALE",
    agreeTitle:            "Avtaler",
    agreeNewBtn:           "+ Ny avtale",
    agreeTabActive:        "Aktive",
    agreeTabConfirm:       "Til bekreftelse",
    agreeTabDone:          "Fullført",
    agreeTabDispute:       "Tvister",
    agreeEmpty:            "Ingen avtaler ennå",
    agreeEmptyDesc:        "Opprett en tjenesteavtale med en annen bruker.",
    agreeOpenBtn:          "Åpne",
    agreeStatusPending:    "Venter på aksept",
    agreeStatusAccepted:   "Akseptert",
    agreeStatusFunded:     "Midler holdt",
    agreeStatusInProgress: "Pågår",
    agreeStatusSubmitted:  "Venter på bekreftelse",
    agreeStatusCompleted:  "Bekreftet",
    agreeStatusReleased:   "Gjort opp",
    agreeStatusDisputed:   "Tvist",
    agreeStatusCancelled:  "Avbrutt",
    agreeNewTitle:         "Ny avtale",
    agreeFieldTitle:       "Tittel",
    agreeFieldDesc:        "Beskrivelse",
    agreeFieldWorker:      "Tjenesteleverandør",
    agreeFieldCategory:    "Kategori",
    agreeFieldAmount:      "Beløp",
    agreeFieldCurrency:    "Valuta",
    agreeFieldDeadline:    "Frist",
    agreeFieldTerms:       "Fullføringsbetingelser",
    agreeFieldProof:       "Påkrevd bevis",
    agreeProofPhoto:       "Fotodokumentasjon",
    agreeProofNote:        "Skriftlig notat",
    agreeSendBtn:          "Send til aksept",
    agreeFundNote:         "Midler vil bli holdt i sandbox-lommeboken og frigjort kun etter at du bekrefter fullføring.",
    agreeDisputeNote:      "Ved tvist, kontakt support.",
    agreeBtnAccept:        "Aksepter avtale",
    agreeBtnSubmit:        "Merk som fullført",
    agreeBtnFund:          "Hold midler",
    agreeBtnConfirm:       "Bekreft fullføring",
    agreeBtnDispute:       "Rapporter problem",
    agreeBtnCancel:        "Avbryt",
    agreeChatPlaceholder:  "Melding om avtalen…",
    agreeSendMsg:          "Send",
    agreeEvents:           "Historikk",
    agreeEvtCreated:       "Avtale opprettet",
    agreeEvtAccepted:      "Avtale akseptert",
    agreeEvtFunded:        "Midler holdt i escrow",
    agreeEvtSubmitted:     "Arbeid levert",
    agreeEvtProofImage:    "Bevissbilde vedlagt",
    agreeEvtCompleted:     "Fullføring bekreftet",
    agreeEvtReleased:      "Midler frigitt til utfører",
    agreeEvtDisputed:      "Tvist opprettet",
    agreeEvtCancelled:     "Avtale kansellert",
    agreeDisputePlaceholder: "Beskriv problemet…",
    agreeSubmitPlaceholder:  "Beskriv hva du gjorde…",
    agreePlaceholderTitle:   "F.eks. Luftetur med hund, mandag morgen",
    agreePlaceholderDesc:    "Beskriv kort hva som skal utføres",
    agreePlaceholderWorker:  "Søk etter navn, e-post eller brukernavn",
    agreePlaceholderTerms:   "Hva utgjør vellykket fullføring…",
    agreeNoFunds:          "Utilstrekkelig saldo",
    agreeErrNotFound:      "Avtalen finnes ikke",
    agreeErrNoAccess:      "Ingen tilgang",
    agreeErrFailedAccept:  "Kunne ikke akseptere",
    agreeErrFailedSubmit:  "Kunne ikke sende inn",
    agreeErrFailedFund:    "Kunne ikke holde midler",
    agreeErrFailedConfirm: "Kunne ikke bekrefte",
    agreeErrFailedDispute: "Kunne ikke åpne tvist",
    agreeErrImageSize:     "Bildet må være under 25 MB",
    agreeErrFailedPropose: "Kunne ikke sende endringsforslag",
    agreeErrFailedApply:          "Kunne ikke godta endringen",
    agreeErrFailedReject:         "Kunne ikke avslå endringen",
    agreeErrFundsAlreadyReleased: "Midlene er allerede utbetalt",
    agreeErrSelfContract:         "Oppdragsgiver og utfører kan ikke være samme person",
    agreeErrNotLoggedIn:          "Ikke innlogget",
    agreeErrSaveFailed:           "Feil ved lagring av avtale",
    agreeContractChat:     "Avtalechat",
    agreeFrom:             "Oppdragsgiver",
    agreeTo:               "Utfører",
    agreeDeadline:         "Frist",
    agreeAmount:           "Beløp",
    agreeCategory:         "Kategori",
    agreeCatDog:           "Hundetur",
    agreeCatTransport:     "Transport",
    agreeCatRepair:        "Reparasjon / håndverk",
    agreeCatCleaning:      "Rengjøring",
    agreeCatShopping:      "Handling",
    agreeCatOther:         "Annet",
    agreeOpenContract:     "Åpne avtale",
    agreeNewContract:      "Ny avtale",
    agreeInChatBtn:        "Avtale",
    agreeTmplSection:       "Velg mal",
    agreeTmplDog:           "Hundetur",
    agreeTmplCleaning:      "Rengjøring",
    agreeTmplTransport:     "Transport",
    agreeTmplMoving:        "Flyttehjelp",
    agreeTmplRepair:        "Reparasjon",
    agreeTmplShopping:      "Handling",
    agreeTmplCare:          "Omsorg",
    agreeTmplLoan:          "Utlån av ting",
    agreeTmplOther:         "Annet",
    agreeTmplDogTerms:      "Utfører forplikter seg til å gå tur med hunden i minst 30 minutter. Bevis: kort notat eller bilde etter turen.",
    agreeTmplCleaningTerms: "Utfører rengjør angitte rom etter avtale. Bevis: bilde etter rengjøring eller skriftlig notat.",
    agreeTmplTransportTerms:"Utfører henter og leverer angitte person/ting til rett tid, iht. avtalt rute.",
    agreeTmplMovingTerms:   "Utfører hjelper med pakking og transport av ting. Oppdragsgiver bekrefter etter fullføring.",
    agreeTmplRepairTerms:   "Utfører reparerer angitt utstyr. Bevis: bilde etter reparasjon eller demonstrasjon av at det fungerer.",
    agreeTmplShoppingTerms: "Utfører kjøper angitte produkter og leverer dem. Bevis: kvittering eller bilde av varene.",
    agreeTmplCareTerms:     "Utfører yter omsorg i avtalt tid. Bevis: skriftlig notat om forløpet.",
    agreeTmplLoanTerms:     "Gjenstanden lånes ut i perioden angitt i avtalen og returneres i uskadd stand.",
    agreeTmplOtherTerms:    "Utfører utfører tjenesten etter individuelle avtaler. Bevis etter oppdragsgivers krav.",
    agreeAiHelperBtn:       "Hjelp til å skrive betingelser",
    agreeDepositToggle:     "Legg til depositum / sikkerhet",
    agreeDepositAmount:     "Depositumbeløp",
    agreeDepositCurrency:   "Depositumvaluta",
    agreeDepositReturnRule: "Returvilkår",
    agreeDepositPlaceholder:"F.eks. Depositum tilbakebetales når gjenstanden returneres uskadd.",
    agreeCompletionCriteria:            "Hva som regnes som fullført",
    agreeCompletionCriteriaPlaceholder: "Beskriv nøyaktig hva som vil utgjøre vellykket fullføring…",
    agreeSecuritySection:               "Sikkerhetsregler",
    agreeSecurityText:                  "Vær presis om hva som utgjør fullføring. Midler frigjøres kun etter din bekreftelse. Hold alle avtaler i appen.",
    agreeSelfError:                     "Du kan ikke opprette en avtale med deg selv",
    agreeWarnHighAmount:                "Høyt beløp. Verifiser den andre parten eller start med et lavere beløp.",
    agreeWarnNoPhoto:                   "Uten fotodokumentasjon er det vanskeligere å bevise fullføring. Vurder å kreve fotodokumentasjon.",
    agreeWorkerNoHistory:               "Denne personen har ingen historikk ennå. Vurder å starte med et lavere beløp.",
    agreeAcceptanceSection:             "Akseptstatus",
    agreeCreatorAcceptedLabel:          "Oppdragsgiver: akseptert",
    agreeWorkerAcceptedLabel:           "Utfører: akseptert",
    agreeCreatorPendingLabel:           "Oppdragsgiver: venter",
    agreeWorkerPendingLabel:            "Utfører: venter",
    agreeBtnWorkerAccept:               "Jeg aksepterer avtalens vilkår",
    agreeFundAvailable:                 "Tilgjengelig",
    agreeFundShortfall:                 "Underskudd",
    agreeFundHoldNote2:                 "Midler holdes — utfører mottar dem kun etter din bekreftelse",
    agreeSubmitConfirmCheck:            "Jeg bekrefter at jeg fullførte oppgaven i henhold til avtalens vilkår",
    agreeSubmitPhotoRequired:           "Foto er påkrevd som bevis på fullføring",
    agreeProofCardTitle:                "Fullføringsbevis",
    agreeProofCardNote:                 "Utførers notat",
    agreeProofCardPhoto:                "Foto",
    agreeProofCardDate:                 "Levert",
    agreeDisputeReason:                 "Tvistgrunn",
    agreeDisputeReason1:                "Tjeneste ikke utført",
    agreeDisputeReason2:                "Delvis utført",
    agreeDisputeReason3:                "Bevis er uklart",
    agreeDisputeReason4:                "Fristmisforhold",
    agreeDisputeReason5:                "Beløpsmisforhold",
    agreeDisputeReason6:                "Annen grunn",
    agreeTimelineTitle:                 "Avtalefremgang",
    agreeTimelineStep1:                 "Opprettet",
    agreeTimelineStep2:                 "Akseptert",
    agreeTimelineStep3:                 "Midler holdt",
    agreeTimelineStep4:                 "Arbeid levert",
    agreeTimelineStep5:                 "Bekreftelse",
    agreeTimelineStep6:                 "Midler frigitt",
    agreeChatSecurityNote:              "Hold all kommunikasjon i appen for din sikkerhet",
    agreeChangeBtn:                     "Foreslå endring",
    agreeChangeTitle:                   "Foreslå avtaleendring",
    agreeChangeNewDeadline:             "Ny frist (valgfritt)",
    agreeChangeNewAmount:               "Nytt beløp (valgfritt)",
    agreeChangeAmountLocked:            "Beløpet kan ikke endres mens midlene holdes",
    agreeChangeNewTerms:                "Nye vilkår (valgfritt)",
    agreeChangeNote:                    "Merknad til den andre parten",
    agreeChangeSend:                    "Send forslag",
    agreeChangePending:                 "Venter på svar",
    agreeChangeAccept:                  "Aksepter endring",
    agreeChangeReject:                  "Avvis",
    agreeChangeAccepted:                "Endring akseptert",
    agreeChangeRejected:                "Endring avvist",
    agreeEvtChangeProposed:             "Endring foreslått",
    agreeEvtChangeAccepted:             "Endring akseptert",
    agreeEvtChangeRejected:             "Endring avvist",
    agreeEvtWorkerAccepted:             "Utfører aksepterte vilkårene",
    agreeSelectPlaceholder:             "— velg —",
    agreePhotoSelected:                 "Foto valgt ✓",
    agreeRateBtn:                       "Vurder samarbeidet",
    ratingModalTitle:                   "Vurder samarbeidet",
    ratingModalStars:                   "Din vurdering",
    ratingModalComment:                 "Legg igjen en kommentar (valgfritt)",
    ratingModalOnTime:                  "Ble det gjort til rett tid?",
    ratingModalRecommend:               "Vil du anbefale denne personen?",
    ratingModalSubmit:                  "Send vurdering",
    ratingModalSkip:                    "Hopp over for nå",
    ratingModalThanks:                  "Takk for vurderingen!",
    ratingNoRatings:                    "Ingen vurderinger ennå",
    ratingAvg:                          "Gjennomsnittskarakteren",
    ratingCount:                        "Vurderinger",
    ratingRecommended:                  "Anbefalt",
    ratingCompleted:                    "Fullført",
    levelNew:                           "Ny",
    levelVerified:                      "Verifisert",
    levelTrusted:                       "Betrodd",
    levelTop:                           "Topputfører",
    levelSuper:                         "Super hjelper",
    reputationSection:                  "Omdømme",
    agreeWorkerReputation:              "Utførerens omdømme",
    ratingYes:                          "Ja",
    ratingNo:                           "Nei",
    ratingCompletedAgreements:          "Fullført",
    ratingBuildReputation:              "Fullfør avtaler for å bygge omdømmet ditt.",
    agreeStepper1:        "1. Oppgave",
    agreeStepper2:        "2. Prising",
    agreeStepper3:        "3. Bekreft",
    agreeSecurePayTitle:  "Sikker betaling",
    agreeSecurePayDesc:   "Midler blokkeres og utbetales kun etter at fullføring er bekreftet.",
    agreeNewCategories:   "Velg kategori",
    agreeCatRenovation:   "Renovering",
    agreeCatCarpenter:    "Tømmermann",
    agreeCatJoiner:       "Snekker",
    agreePricingType:     "Prisingsmetode",
    agreePricingFixed:    "Fast pris",
    agreePricingM2:       "Pris per m\u00B2",
    agreePricingHourly:   "Per time",
    agreePricingPiece:    "Per stykk",
    agreePricingMixed:    "Blandet",
    agreePricingDetails:  "Prisdetaljer",
    agreePricingSummary:  "Kostnadssammendrag",
    agreePricingArea:     "Areal (m\u00B2)",
    agreePricingPriceM2:  "Pris per 1 m\u00B2",
    agreePricingMaterials:"Materialer",
    agreePricingExtra:    "Ekstra kostnader",
    agreePricingLabor:    "Arbeidskraft",
    agreePricingTotal:    "Totalt",
    agreeFixedFinalPrice: "Fast sluttbeløp",
    agreeHourlyRate:      "Timerate",
    agreeHoursCount:      "Antall timer",
    agreeHoursMax:        "Maks timer",
    agreePieceCount:      "Antall stykker",
    agreePiecePrice:      "Pris per stykk",
    agreePieceDesc:       "Beskrivelse av elementer",
    agreeMixedTitle:      "Blandet prising",
    agreeWorkScopeTitle:  "Arbeidsomfang",
    agreeWorkScopeWhat:   "Hva skal utføres",
    agreeWorkScopeExcluded:"Hva er ikke inkludert",
    agreeMaterialsBy:     "Hvem leverer materialer",
    agreeMaterialsClient: "Oppdragsgiver",
    agreeMaterialsWorker: "Utfører",
    agreeMaterialsSeparate:"Separat fakturering",
    agreeMaterialsIncluded:"Inkludert i pris",
    agreeConditionsTitle: "Akseptbetingelser",
    agreeAiHelperBtnShort:"AI: Hjelp til å skrive",
    agreeStagesTitle:     "Arbeidsfaser",
    agreeAddStage:        "Legg til fase",
    agreeProofsTitle:     "Påkrevd dokumentasjon",
    agreeProofAfter:      "Bilde av fullført arbeid",
    agreeProofBefore:     "Bilde før start",
    agreeProofMessage:    "Fullføringsmelding",
    agreeProofBothSides:  "Begge parter bekrefter",
    agreeProofLocation:   "Lokasjon / tidsstempel",
    agreeDeadlineTitle:   "Frist",
    agreeDeadlineToday:   "I dag",
    agreeDeadlineTomorrow:"I morgen",
    agreeDeadline7d:      "7 dager",
    agreeDeadline14d:     "14 dager",
    agreeDeadlineCustom:  "Velg dato",
    agreeSummaryTitle:    "Avtalesammendrag",
    agreeCreateBtn:       "Opprett ideell avtale",
    notifAll:             "Alle",
    notifMessages:        "Meldinger",
    notifPayments:        "Betalinger",
    notifContracts:       "Avtaler",
    notifSystem:          "System",
    notifSecurity:        "Sikkerhet",
    notifEmpty:           "Ingen varsler",
    notifEmptyDesc:       "Innboksen er tom. Ingenting å se her.",
    notifMarkAllRead:     "Merk alle som lest",
    notifDelivery:        "Leveringskanaler",
    notifPerCategory:     "Varslingstyper",
    notifInApp:           "I-app",
    notifPushToggle:      "Push",
    notifQuietHours:      "Stille timer",
    notifQuietFrom:       "Fra",
    notifQuietTo:         "Til",
    notifPrefsSaved:      "Preferanser lagret",
    notifTestPanel:       "Test varsler",
    notifTestSend:        "Send test",
    notifTestSendPush:    "Send også push",
    notifTestTitle:       "Tittel",
    notifTestMessage:     "Melding",
    notifTestCategory:    "Kategori",
    notifTestPriority:    "Prioritet",
    notifTestRoute:       "Rute (f.eks. /messages)",
    notifTestSent:        "Testvarsel sendt",
    notifTestTargetUser:  "Mål-bruker-ID",
    notifPriorityLow:     "Lav",
    notifPriorityNormal:  "Normal",
    notifPriorityHigh:    "Høy",
    notifPriorityCritical:"Kritisk",
    notifFilterAll:       "Alle",
    notifFilterNew:       "Nye",
    notifFilterImportant: "Viktig",
    notifDelete:          "Slett",
    notifQuietModeTitle:  "Stille modus",
    notifImportantOnly:   "Kun viktig i stille modus",
    notifDailySummary:    "Daglig oppsummering",
    notifQuietModeDesc:   "Kun kritiske varsler og varsler med høy prioritet vil varsle deg i stille modus.",
    notifScenarioGroupedMsg: "3 meldinger (gruppert)",
    notifClearQuiet:      "Fjern",
    notifQuietHoursTitle: "Stille timer",
  },
  es: {
    privateClient:    "CLIENTE PRIVADO",
    totalWealth:      "PATRIMONIO TOTAL",
    platinum:         "PLATINO",
    addFunds:         "+ Añadir fondos",
    transfer:         "↗ Transferir",
    forecast:         "PREVISIÓN",
    request:          "SOLICITUD",
    invest:           "INVERTIR",
    cards:            "TARJETAS",
    cashFlow:         "FLUJO DE CAJA",
    recentOperations: "Operaciones recientes",
    seeAll:           "Ver todo",
    home:             "INICIO",
    visualTheme:      "TEMA VISUAL",
    obsidianGold:     "Obsidiana Dorada",
    arcticPlatinum:   "Platino Ártico",
    graphiteEmerald:  "Grafito Esmeralda",
    dark:             "OSCURO",
    light:            "CLARO",
    medium:           "MEDIO",
    appPreferences:   "Preferencias de app",
    personalise:      "Personaliza tu experiencia",
    visualExperience: "Experiencia visual",
    themeDesc:        "Cada paleta está diseñada en torno a un arquetipo de lujo psicológico",
    localisation:     "Localización",
    language:         "Idioma",
    primaryCurrency:  "Moneda principal",
    privacyExp:       "Privacidad",
    hideBalances:     "Ocultar saldos",
    hideBalancesDesc: "Difuminar importes en público",
    appLock:          "Bloqueo de app",
    appLockDesc:      "Requerir autenticación al reanudar",
    edit:             "Editar",
    active:           "ACTIVO",
    sovereignDark:    "OSCURIDAD SOBERANA",
    pristineLight:    "LUZ PRÍSTINA",
    forestPower:      "PODER DEL BOSQUE",
    powerPrestige:    "Poder · Prestigio · Profundidad",
    clarityTrust:     "Claridad · Confianza · Precisión",
    growthMastery:    "Crecimiento · Maestría · Naturaleza",
    obsidianDesc:     "Forjado en medianoche. Sellado en oro. La paleta de la autoridad — atemporal como una bóveda, cálida como una llama.",
    platinumDesc:     "La luminancia de la riqueza cristalina. Ligero como el horizonte al amanecer — puro, transparente e inflexible.",
    emeraldDesc:      "Autoridad ancestral de tierras raras. Las reservas de esmeralda se extienden profundamente — donde la naturaleza y el capital convergen, la riqueza se multiplica.",
    themeUpdated:     "Tema actualizado",
    themeActive:      "ahora está activo.",
    languageSet:      "Idioma actualizado",
    send:                  "ENVIAR",
    messages:              "CHAT",
    currencies:            "DIVISAS",
    manageCurrencies:      "GESTIONAR DIVISAS",
    addCurrency:           "Añadir divisa",
    primaryBadge:          "PRINCIPAL",
    setPrimary:            "Establecer principal",
    removeCurrency:        "Eliminar",
    selectCurrency:        "SELECCIONAR DIVISA",
    exchange:              "CAMBIAR",
    currencyExchange:      "CAMBIO DE DIVISAS",
    amount:                "Importe...",
    convert:               "CONVERTIR",
    received:              "Recibido",
    errorPrefix:           "Error: ",
    yourCards:             "TUS TARJETAS",
    activeCards:           "activas",
    noCards:               "NINGUNA",
    activeStatus:          "ACTIVAS",
    topupLoginAgain:       "Por favor, inicia sesión de nuevo.",
    topupEnterValidAmount: "Introduce un importe válido.",
    topupStripeError:      "Error del servidor de Stripe.",
    topupVerifying:        "Verificando el pago...",
    topupPleaseWait:       "Por favor, espera un momento.",
    topupPaymentConfirmed: "¡Pago confirmado!",
    topupAddedToWallet:    "Añadido a tu cartera de {cur}.",
    topupBalancePending:   "Tu saldo se actualizará automáticamente cuando Stripe confirme el pago (unos segundos).",
    topupBackToWallet:     "Volver a la cartera",
    topupPaymentCanceled:  "Pago cancelado",
    topupNothingCharged:   "No se ha cargado nada a tu tarjeta.",
    topupTryAgain:         "Intentar de nuevo",
    topupBackToHome:       "Volver al inicio",
    topupTitle:            "Añadir fondos",
    topupSelectCurrency:   "SELECCIONAR DIVISA",
    topupEnterAmountLabel: "INTRODUCE EL IMPORTE",
    topupYoullAdd:         "AÑADIRÁS",
    topupRedirecting:      "Redirigiendo...",
    topupAddViaCard:       "Añadir con tarjeta",
    topupStripeNote:       "El saldo se actualiza automáticamente después de que Stripe confirme tu pago.",
    unknownError:          "Se ha producido un error desconocido.",
    agreements:            "CONTRATO",
    agreeTitle:            "Contratos",
    agreeNewBtn:           "+ Nuevo contrato",
    agreeTabActive:        "Activos",
    agreeTabConfirm:       "Por confirmar",
    agreeTabDone:          "Completados",
    agreeTabDispute:       "Disputas",
    agreeEmpty:            "Aún no tienes contratos",
    agreeEmptyDesc:        "Crea un acuerdo de servicio con otro usuario.",
    agreeOpenBtn:          "Abrir",
    agreeStatusPending:    "Esperando aceptación",
    agreeStatusAccepted:   "Aceptado",
    agreeStatusFunded:     "Fondos retenidos",
    agreeStatusInProgress: "En progreso",
    agreeStatusSubmitted:  "Esperando confirmación",
    agreeStatusCompleted:  "Confirmado",
    agreeStatusReleased:   "Liquidado",
    agreeStatusDisputed:   "Disputa",
    agreeStatusCancelled:  "Cancelado",
    agreeNewTitle:         "Nuevo contrato",
    agreeFieldTitle:       "Título",
    agreeFieldDesc:        "Descripción",
    agreeFieldWorker:      "Proveedor de servicio",
    agreeFieldCategory:    "Categoría",
    agreeFieldAmount:      "Importe",
    agreeFieldCurrency:    "Divisa",
    agreeFieldDeadline:    "Fecha límite",
    agreeFieldTerms:       "Condiciones de finalización",
    agreeFieldProof:       "Prueba requerida",
    agreeProofPhoto:       "Foto de prueba",
    agreeProofNote:        "Nota escrita",
    agreeSendBtn:          "Enviar para aceptación",
    agreeFundNote:         "Los fondos se retendrán en tu cartera sandbox y se liberarán solo cuando confirmes la finalización.",
    agreeDisputeNote:      "En caso de disputa, contacta con soporte.",
    agreeBtnAccept:        "Aceptar contrato",
    agreeBtnSubmit:        "Marcar como completado",
    agreeBtnFund:          "Retener fondos",
    agreeBtnConfirm:       "Confirmar finalización",
    agreeBtnDispute:       "Reportar problema",
    agreeBtnCancel:        "Cancelar",
    agreeChatPlaceholder:  "Mensaje sobre el contrato…",
    agreeSendMsg:          "Enviar",
    agreeEvents:           "Historial",
    agreeEvtCreated:       "Acuerdo creado",
    agreeEvtAccepted:      "Acuerdo aceptado",
    agreeEvtFunded:        "Fondos retenidos en escrow",
    agreeEvtSubmitted:     "Trabajo enviado",
    agreeEvtProofImage:    "Imagen de prueba adjunta",
    agreeEvtCompleted:     "Finalización confirmada",
    agreeEvtReleased:      "Fondos transferidos al proveedor",
    agreeEvtDisputed:      "Disputa iniciada",
    agreeEvtCancelled:     "Acuerdo cancelado",
    agreeDisputePlaceholder: "Describe el problema…",
    agreeSubmitPlaceholder:  "Describe lo que hiciste…",
    agreePlaceholderTitle:   "Ej. Paseo de perro, lunes por la mañana",
    agreePlaceholderDesc:    "Describe brevemente el servicio a realizar",
    agreePlaceholderWorker:  "Buscar por nombre, email o usuario",
    agreePlaceholderTerms:   "¿Qué constituye la finalización exitosa…",
    agreeNoFunds:          "Saldo insuficiente",
    agreeErrNotFound:      "Acuerdo no encontrado",
    agreeErrNoAccess:      "Sin acceso",
    agreeErrFailedAccept:  "Error al aceptar",
    agreeErrFailedSubmit:  "Error al enviar",
    agreeErrFailedFund:    "Error al retener fondos",
    agreeErrFailedConfirm: "Error al confirmar",
    agreeErrFailedDispute: "Error al abrir disputa",
    agreeErrImageSize:     "La imagen debe ser menor de 25 MB",
    agreeErrFailedPropose: "Error al enviar propuesta de cambio",
    agreeErrFailedApply:          "Error al aceptar el cambio",
    agreeErrFailedReject:         "Error al rechazar el cambio",
    agreeErrFundsAlreadyReleased: "Los fondos ya han sido liberados",
    agreeErrSelfContract:         "El creador y el ejecutor no pueden ser la misma persona",
    agreeErrNotLoggedIn:          "No has iniciado sesión",
    agreeErrSaveFailed:           "Error al guardar el contrato",
    agreeContractChat:     "Chat del contrato",
    agreeFrom:             "Creador",
    agreeTo:               "Ejecutor",
    agreeDeadline:         "Fecha límite",
    agreeAmount:           "Importe",
    agreeCategory:         "Categoría",
    agreeCatDog:           "Pasear el perro",
    agreeCatTransport:     "Transporte",
    agreeCatRepair:        "Reparación / mantenimiento",
    agreeCatCleaning:      "Limpieza",
    agreeCatShopping:      "Compras",
    agreeCatOther:         "Otro",
    agreeOpenContract:     "Abrir contrato",
    agreeNewContract:      "Nuevo contrato",
    agreeInChatBtn:        "Contrato",
    agreeTmplSection:       "Elegir plantilla",
    agreeTmplDog:           "Pasear al perro",
    agreeTmplCleaning:      "Limpieza",
    agreeTmplTransport:     "Transporte",
    agreeTmplMoving:        "Mudanza",
    agreeTmplRepair:        "Reparación",
    agreeTmplShopping:      "Compras",
    agreeTmplCare:          "Cuidados",
    agreeTmplLoan:          "Préstamo de objeto",
    agreeTmplOther:         "Otro",
    agreeTmplDogTerms:      "El ejecutor se compromete a pasear al perro al menos 30 minutos. Prueba: nota corta o foto tras el paseo.",
    agreeTmplCleaningTerms: "El ejecutor limpiará las habitaciones indicadas según lo acordado. Prueba: foto tras la limpieza o nota escrita.",
    agreeTmplTransportTerms:"El ejecutor recogerá y entregará a la persona/objeto indicado a tiempo, según la ruta acordada.",
    agreeTmplMovingTerms:   "El ejecutor ayudará con el embalaje y transporte de objetos. El creador confirma tras la finalización.",
    agreeTmplRepairTerms:   "El ejecutor reparará el equipo indicado. Prueba: foto tras la reparación o demostración de funcionamiento.",
    agreeTmplShoppingTerms: "El ejecutor comprará los productos indicados y los entregará. Prueba: ticket o foto de los artículos.",
    agreeTmplCareTerms:     "El ejecutor prestará cuidados durante el tiempo acordado. Prueba: nota escrita sobre el transcurso.",
    agreeTmplLoanTerms:     "El objeto se presta por el período especificado en el acuerdo y se devuelve en estado intacto.",
    agreeTmplOtherTerms:    "El ejecutor realizará el servicio según acuerdos individuales. Prueba según los requisitos del creador.",
    agreeAiHelperBtn:       "Ayuda a redactar condiciones",
    agreeDepositToggle:     "Añadir depósito / garantía",
    agreeDepositAmount:     "Importe del depósito",
    agreeDepositCurrency:   "Divisa del depósito",
    agreeDepositReturnRule: "Condición de devolución",
    agreeDepositPlaceholder:"Ej. El depósito se devuelve cuando el objeto sea devuelto sin daños.",
    agreeCompletionCriteria:            "Qué cuenta como completado",
    agreeCompletionCriteriaPlaceholder: "Describe exactamente qué constituirá la finalización exitosa…",
    agreeSecuritySection:               "Normas de seguridad",
    agreeSecurityText:                  "Sé preciso sobre qué constituye la finalización. Los fondos solo se liberan tras tu confirmación. Mantén todos los acuerdos en la app.",
    agreeSelfError:                     "No puedes crear un contrato contigo mismo",
    agreeWarnHighAmount:                "Importe elevado. Verifica a la otra parte o empieza con un importe menor.",
    agreeWarnNoPhoto:                   "Sin foto como prueba es más difícil demostrar la finalización. Considera requerir foto.",
    agreeWorkerNoHistory:               "Esta persona no tiene historial aún. Considera empezar con un importe menor.",
    agreeAcceptanceSection:             "Estado de aceptación",
    agreeCreatorAcceptedLabel:          "Creador: aceptado",
    agreeWorkerAcceptedLabel:           "Ejecutor: aceptado",
    agreeCreatorPendingLabel:           "Creador: pendiente",
    agreeWorkerPendingLabel:            "Ejecutor: pendiente",
    agreeBtnWorkerAccept:               "Acepto los términos del contrato",
    agreeFundAvailable:                 "Disponible",
    agreeFundShortfall:                 "Falta",
    agreeFundHoldNote2:                 "Fondos retenidos — el ejecutor los recibe solo tras tu confirmación",
    agreeSubmitConfirmCheck:            "Confirmo que he completado la tarea según las condiciones del contrato",
    agreeSubmitPhotoRequired:           "La foto es obligatoria como prueba de finalización",
    agreeProofCardTitle:                "Prueba de finalización",
    agreeProofCardNote:                 "Nota del ejecutor",
    agreeProofCardPhoto:                "Foto",
    agreeProofCardDate:                 "Enviado",
    agreeDisputeReason:                 "Motivo de la disputa",
    agreeDisputeReason1:                "Servicio no realizado",
    agreeDisputeReason2:                "Realizado parcialmente",
    agreeDisputeReason3:                "La prueba no es clara",
    agreeDisputeReason4:                "La fecha no coincide",
    agreeDisputeReason5:                "El importe no coincide",
    agreeDisputeReason6:                "Otro motivo",
    agreeTimelineTitle:                 "Progreso del contrato",
    agreeTimelineStep1:                 "Creado",
    agreeTimelineStep2:                 "Aceptado",
    agreeTimelineStep3:                 "Fondos retenidos",
    agreeTimelineStep4:                 "Trabajo enviado",
    agreeTimelineStep5:                 "Confirmación",
    agreeTimelineStep6:                 "Fondos liberados",
    agreeChatSecurityNote:              "Mantén toda la comunicación en la app para tu protección",
    agreeChangeBtn:                     "Proponer cambio",
    agreeChangeTitle:                   "Proponer cambio de contrato",
    agreeChangeNewDeadline:             "Nueva fecha límite (opcional)",
    agreeChangeNewAmount:               "Nuevo importe (opcional)",
    agreeChangeAmountLocked:            "El importe no puede cambiarse mientras los fondos están retenidos",
    agreeChangeNewTerms:                "Nuevas condiciones (opcional)",
    agreeChangeNote:                    "Nota para la otra parte",
    agreeChangeSend:                    "Enviar propuesta",
    agreeChangePending:                 "Esperando respuesta",
    agreeChangeAccept:                  "Aceptar cambio",
    agreeChangeReject:                  "Rechazar",
    agreeChangeAccepted:                "Cambio aceptado",
    agreeChangeRejected:                "Cambio rechazado",
    agreeEvtChangeProposed:             "Cambio propuesto",
    agreeEvtChangeAccepted:             "Cambio aceptado",
    agreeEvtChangeRejected:             "Cambio rechazado",
    agreeEvtWorkerAccepted:             "Ejecutor aceptó los términos",
    agreeSelectPlaceholder:             "— seleccionar —",
    agreePhotoSelected:                 "Foto seleccionada ✓",
    agreeRateBtn:                       "Valorar colaboración",
    ratingModalTitle:                   "Valorar la colaboración",
    ratingModalStars:                   "Tu valoración",
    ratingModalComment:                 "Deja un comentario (opcional)",
    ratingModalOnTime:                  "¿Se realizó a tiempo?",
    ratingModalRecommend:               "¿Recomendarías a esta persona?",
    ratingModalSubmit:                  "Enviar valoración",
    ratingModalSkip:                    "Omitir por ahora",
    ratingModalThanks:                  "¡Gracias por tu valoración!",
    ratingNoRatings:                    "Sin valoraciones aún",
    ratingAvg:                          "Valoración media",
    ratingCount:                        "Valoraciones",
    ratingRecommended:                  "Recomendado",
    ratingCompleted:                    "Completados",
    levelNew:                           "Nuevo",
    levelVerified:                      "Verificado",
    levelTrusted:                       "De confianza",
    levelTop:                           "Top Ejecutor",
    levelSuper:                         "Super Colaborador",
    reputationSection:                  "Reputación",
    agreeWorkerReputation:              "Reputación del ejecutor",
    ratingYes:                          "Sí",
    ratingNo:                           "No",
    ratingCompletedAgreements:          "Completados",
    ratingBuildReputation:              "Completa acuerdos para construir tu reputación.",
    agreeStepper1:        "1. Tarea",
    agreeStepper2:        "2. Precio",
    agreeStepper3:        "3. Confirmar",
    agreeSecurePayTitle:  "Pago seguro",
    agreeSecurePayDesc:   "Los fondos se bloquean y se liberan solo tras confirmar la finalización.",
    agreeNewCategories:   "Elige categoría",
    agreeCatRenovation:   "Renovación",
    agreeCatCarpenter:    "Carpintero",
    agreeCatJoiner:       "Ebanista",
    agreePricingType:     "Método de precio",
    agreePricingFixed:    "Precio fijo",
    agreePricingM2:       "Precio por m\u00B2",
    agreePricingHourly:   "Por hora",
    agreePricingPiece:    "Por pieza",
    agreePricingMixed:    "Mixto",
    agreePricingDetails:  "Detalles de precio",
    agreePricingSummary:  "Resumen de costes",
    agreePricingArea:     "Superficie (m\u00B2)",
    agreePricingPriceM2:  "Precio por 1 m\u00B2",
    agreePricingMaterials:"Materiales",
    agreePricingExtra:    "Costes extra",
    agreePricingLabor:    "Mano de obra",
    agreePricingTotal:    "Total",
    agreeFixedFinalPrice: "Precio final fijo",
    agreeHourlyRate:      "Tarifa por hora",
    agreeHoursCount:      "N\u00FAmero de horas",
    agreeHoursMax:        "L\u00EDmite máximo de horas",
    agreePieceCount:      "N\u00FAmero de piezas",
    agreePiecePrice:      "Precio por pieza",
    agreePieceDesc:       "Descripción de elementos",
    agreeMixedTitle:      "Precio mixto",
    agreeWorkScopeTitle:  "Alcance del trabajo",
    agreeWorkScopeWhat:   "Qué debe realizarse exactamente",
    agreeWorkScopeExcluded:"Qué no está incluido",
    agreeMaterialsBy:     "Quién provee materiales",
    agreeMaterialsClient: "Cliente",
    agreeMaterialsWorker: "Ejecutor",
    agreeMaterialsSeparate:"Facturación separada",
    agreeMaterialsIncluded:"Incluido en precio",
    agreeConditionsTitle: "Condiciones de aceptación",
    agreeAiHelperBtnShort:"IA: Ayudar a escribir",
    agreeStagesTitle:     "Fases de trabajo",
    agreeAddStage:        "Añadir fase",
    agreeProofsTitle:     "Pruebas requeridas",
    agreeProofAfter:      "Foto del trabajo terminado",
    agreeProofBefore:     "Foto antes de empezar",
    agreeProofMessage:    "Mensaje de finalización",
    agreeProofBothSides:  "Ambas partes confirman",
    agreeProofLocation:   "Ubicación / marca de tiempo",
    agreeDeadlineTitle:   "Plazo",
    agreeDeadlineToday:   "Hoy",
    agreeDeadlineTomorrow:"Mañana",
    agreeDeadline7d:      "7 días",
    agreeDeadline14d:     "14 días",
    agreeDeadlineCustom:  "Elegir fecha",
    agreeSummaryTitle:    "Resumen del acuerdo",
    agreeCreateBtn:       "Crear acuerdo ideal",
    notifAll:             "Todos",
    notifMessages:        "Mensajes",
    notifPayments:        "Pagos",
    notifContracts:       "Contratos",
    notifSystem:          "Sistema",
    notifSecurity:        "Seguridad",
    notifEmpty:           "Sin notificaciones",
    notifEmptyDesc:       "Tu bandeja está vacía. Nada que ver aquí.",
    notifMarkAllRead:     "Marcar todo como leído",
    notifDelivery:        "Canales de entrega",
    notifPerCategory:     "Tipos de notificación",
    notifInApp:           "En la app",
    notifPushToggle:      "Push",
    notifQuietHours:      "Horas silenciosas",
    notifQuietFrom:       "Desde",
    notifQuietTo:         "Hasta",
    notifPrefsSaved:      "Preferencias guardadas",
    notifTestPanel:       "Probar notificaciones",
    notifTestSend:        "Enviar prueba",
    notifTestSendPush:    "Enviar también push",
    notifTestTitle:       "Título",
    notifTestMessage:     "Mensaje",
    notifTestCategory:    "Categoría",
    notifTestPriority:    "Prioridad",
    notifTestRoute:       "Ruta (p.ej. /messages)",
    notifTestSent:        "Notificación de prueba enviada",
    notifTestTargetUser:  "ID de usuario destino",
    notifPriorityLow:     "Baja",
    notifPriorityNormal:  "Normal",
    notifPriorityHigh:    "Alta",
    notifPriorityCritical:"Crítica",
    notifFilterAll:       "Todo",
    notifFilterNew:       "Nuevo",
    notifFilterImportant: "Importante",
    notifDelete:          "Eliminar",
    notifQuietModeTitle:  "Modo silencioso",
    notifImportantOnly:   "Solo importante en modo silencioso",
    notifDailySummary:    "Resumen diario",
    notifQuietModeDesc:   "Solo las alertas críticas y de alta prioridad te notificarán en modo silencioso.",
    notifScenarioGroupedMsg: "3 mensajes (agrupados)",
    notifClearQuiet:      "Borrar",
    notifQuietHoursTitle: "Horas silenciosas",
  },
} as const;

export type StringKey = keyof typeof STRINGS.en;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof STRINGS.en;
}

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: STRINGS.en,
});

const VALID_LANGS: Lang[] = ["en", "pl", "no", "es"];

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAppStore();

  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem(StorageKeys.LANG) as Lang;
    if (VALID_LANGS.includes(saved)) return saved;
    const browser = (navigator.language || "en").toLowerCase();
    if (browser.startsWith("pl")) return "pl";
    if (browser.startsWith("no") || browser.startsWith("nb") || browser.startsWith("nn")) return "no";
    if (browser.startsWith("es")) return "es";
    return "en";
  });

  useEffect(() => {
    const serverLang = user?.language as Lang | null | undefined;
    if (serverLang && VALID_LANGS.includes(serverLang) && serverLang !== lang) {
      setLangState(serverLang);
      localStorage.setItem(StorageKeys.LANG, serverLang);
    }
  }, [user?.language]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem(StorageKeys.LANG, l);
    if (user?.id) {
      fetch(`/api/user/${user.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ language: l }),
      }).catch(() => {});
    }
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: STRINGS[lang] as typeof STRINGS.en }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
